# Generated by Django 4.2.5 on 2023-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(default="chat room", max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
